In [1]:
import pandas as pd

In [16]:
df=pd.read_excel(r"E:\Files\Data science\ineuron full stack datascience paid course\Pandas\First class pandas\Attribute DataSet.xlsx")

In [10]:
pd.read_excel(r"Attribute DataSet.xlsx", sheet_name = "Sheet2")

  jhjhlkh okkkjj
0   uhuih     hh
1   uihuh   zugz

In [15]:
pd.read_excel(r"Attribute DataSet.xlsx", sheet_name = "Sheet2", header= None, names=["A","B","C"])

         A       B   C
0  jhjhlkh  okkkjj NaN
1    uhuih      hh NaN
2    uihuh    zugz NaN

In [17]:
df

,Dress_ID,Style,Price,Rating,Size,Season,NeckLine,SleeveLength,waiseline,Material,FabricType,Decoration,Pattern Type,Recommendation
0,1006032852,Sexy,Low,4.6,M,Summer,o-neck,sleevless,empire,NaN,chiffon,ruffles,animal,1
1,1212192089,Casual,Low,0.0,L,Summer,o-neck,Petal,natural,microfiber,NaN,ruffles,animal,0
2,1190380701,vintage,High,0.0,L,Automn,o-neck,full,natural,polyster,NaN,NaN,print,0
3,966005983,Brief,Average,4.6,L,Spring,o-neck,full,natural,silk,chiffon,embroidary,print,1
4,876339541,cute,Low,4.5,M,Summer,o-neck,butterfly,natural,chiffonfabric,chiffon,bow,dot,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,713391965,Casual,Low,4.7,M,Spring,o-neck,full,natural,polyster,NaN,NaN,solid,1
496,722565148,Sexy,Low,4.3,free,Summer,o-neck,full,empire,cotton,NaN,NaN,NaN,0
497,532874347,Casual,Average,4.7,M,Summer,v-neck,full,empire,cotton,NaN,lace,solid,1
498,655464934,Casual,Average,4.6,L,winter,boat-neck,sleevless,empire,silk,broadcloth,applique,print,1
499,919930954,Casual,Low,4.4,free,Summer,v-neck,short,empire,cotton,Corduroy,lace,solid,0

In [18]:
df.head(2)

,Dress_ID,Style,Price,Rating,Size,Season,NeckLine,SleeveLength,waiseline,Material,FabricType,Decoration,Pattern Type,Recommendation
0,1006032852,Sexy,Low,4.6,M,Summer,o-neck,sleevless,empire,NaN,chiffon,ruffles,animal,1
1,1212192089,Casual,Low,0.0,L,Summer,o-neck,Petal,natural,microfiber,NaN,ruffles,animal,0

In [19]:
df.tail(2)
#last record

,Dress_ID,Style,Price,Rating,Size,Season,NeckLine,SleeveLength,waiseline,Material,FabricType,Decoration,Pattern Type,Recommendation
498,655464934,Casual,Average,4.6,L,winter,boat-neck,sleevless,empire,silk,broadcloth,applique,print,1
499,919930954,Casual,Low,4.4,free,Summer,v-neck,short,empire,cotton,Corduroy,lace,solid,0

In [ ]:
# csv format , comma separated format

In [22]:
#reading file and header er nam change
pd.read_csv("haberman.csv", header=None, names=["age", "Patient's year of operation", "Number of positive", "Survival status "])

     age  Patient's year of operation  Number of positive  Survival status
0     30                           64                   1                 1
1     30                           62                   3                 1
2     30                           65                   0                 1
3     31                           59                   2                 1
4     31                           65                   4                 1
..   ...                          ...                 ...               ...
301   75                           62                   1                 1
302   76                           67                   0                 1
303   77                           65                   3                 1
304   78                           65                   1                 2
305   83                           58                   2                 2

[306 rows x 4 columns]

In [26]:
# Separator er maddome change kora 
pd.read_csv("haberman11.csv", sep="@", header=None)

      0   1  2  3
0    30  64  1  1
1    30  62  3  1
2    30  65  0  1
3    31  59  2  1
4    31  65  4  1
..   ..  .. .. ..
301  75  62  1  1
302  76  67  0  1
303  77  65  3  1
304  78  65  1  2
305  83  58  2  2

[306 rows x 4 columns]

In [30]:
pd.read_csv("https://raw.githubusercontent.com/selva86/datasets/master/Prestige.csv")

     education  income  women  prestige  census  type
0        13.11   12351  11.16      68.8    1113  prof
1        12.26   25879   4.02      69.1    1130  prof
2        12.77    9271  15.70      63.4    1171  prof
3        11.42    8865   9.11      56.8    1175  prof
4        14.62    8403  11.68      73.5    2111  prof
..         ...     ...    ...       ...     ...   ...
97        7.58    5562   9.47      35.9    9171    bc
98        7.93    4224   3.59      25.1    9173    bc
99        8.37    4753   0.00      26.1    9313    bc
100      10.00    6462  13.58      42.2    9511    bc
101       8.55    3617  70.87      35.2    9517    bc

[102 rows x 6 columns]

In [39]:
a=pd.read_html("https://www.iplt20.com/stats")

In [40]:
a

[                                                   0  \
 0                                               Role
 1                                               Bats
 2                                                NaN
 3                                                Bio
 4  A 22-year old opening batsman who hails from P...

                                                    1  \
 0                                            Batsman
 1                                                NaN
 2                                                NaN
 3                                                NaN
 4  A 22-year old opening batsman who hails from P...

                                                    2  \
 0                                        Nationality
 1                                              Bowls
 2                                                NaN
 3                                                NaN
 4  A 22-year old opening batsman who hails from P...

                                                    3   4
 0                                             Indian NaN
 1                                                NaN NaN
 2                                                NaN NaN
 3                                                NaN NaN
 4  A 22-year old opening batsman who hails from P... NaN  ]

In [41]:
len(a)

1

In [42]:
a[0]

,0,1,2,3,4
0,Role,Batsman,Nationality,Indian,NaN
1,Bats,NaN,Bowls,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN
3,Bio,NaN,NaN,NaN,NaN
4,A 22-year old opening batsman who hails from P...,A 22-year old opening batsman who hails from P...,A 22-year old opening batsman who hails from P...,A 22-year old opening batsman who hails from P...,NaN

In [44]:
js=pd.read_json("https://api.github.com/repos/pandas-dev/pandas/issues")

In [45]:
js.columns

Index(['url', 'repository_url', 'labels_url', 'comments_url', 'events_url',
       'html_url', 'id', 'node_id', 'number', 'title', 'user', 'labels',
       'state', 'locked', 'assignee', 'assignees', 'milestone', 'comments',
       'created_at', 'updated_at', 'closed_at', 'author_association',
       'active_lock_reason', 'body', 'reactions', 'timeline_url',
       'performed_via_github_app', 'state_reason', 'draft', 'pull_request'],
      dtype='object')

In [47]:
js["user"][0]

{'login': 'MarcoGorelli',
 'id': 33491632,
 'node_id': 'MDQ6VXNlcjMzNDkxNjMy',
 'avatar_url': 'https://avatars.githubusercontent.com/u/33491632?v=4',
 'gravatar_id': '',
 'url': 'https://api.github.com/users/MarcoGorelli',
 'html_url': 'https://github.com/MarcoGorelli',
 'followers_url': 'https://api.github.com/users/MarcoGorelli/followers',
 'following_url': 'https://api.github.com/users/MarcoGorelli/following{/other_user}',
 'gists_url': 'https://api.github.com/users/MarcoGorelli/gists{/gist_id}',
 'starred_url': 'https://api.github.com/users/MarcoGorelli/starred{/owner}{/repo}',
 'subscriptions_url': 'https://api.github.com/users/MarcoGorelli/subscriptions',
 'organizations_url': 'https://api.github.com/users/MarcoGorelli/orgs',
 'repos_url': 'https://api.github.com/users/MarcoGorelli/repos',
 'events_url': 'https://api.github.com/users/MarcoGorelli/events{/privacy}',
 'received_events_url': 'https://api.github.com/users/MarcoGorelli/received_events',
 'type': 'User',
 'site_admin': False}

In [49]:
df=pd.read_excel(r"Attribute DataSet.xlsx")

In [50]:
df

,Dress_ID,Style,Price,Rating,Size,Season,NeckLine,SleeveLength,waiseline,Material,FabricType,Decoration,Pattern Type,Recommendation
0,1006032852,Sexy,Low,4.6,M,Summer,o-neck,sleevless,empire,NaN,chiffon,ruffles,animal,1
1,1212192089,Casual,Low,0.0,L,Summer,o-neck,Petal,natural,microfiber,NaN,ruffles,animal,0
2,1190380701,vintage,High,0.0,L,Automn,o-neck,full,natural,polyster,NaN,NaN,print,0
3,966005983,Brief,Average,4.6,L,Spring,o-neck,full,natural,silk,chiffon,embroidary,print,1
4,876339541,cute,Low,4.5,M,Summer,o-neck,butterfly,natural,chiffonfabric,chiffon,bow,dot,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,713391965,Casual,Low,4.7,M,Spring,o-neck,full,natural,polyster,NaN,NaN,solid,1
496,722565148,Sexy,Low,4.3,free,Summer,o-neck,full,empire,cotton,NaN,NaN,NaN,0
497,532874347,Casual,Average,4.7,M,Summer,v-neck,full,empire,cotton,NaN,lace,solid,1
498,655464934,Casual,Average,4.6,L,winter,boat-neck,sleevless,empire,silk,broadcloth,applique,print,1
499,919930954,Casual,Low,4.4,free,Summer,v-neck,short,empire,cotton,Corduroy,lace,solid,0

In [51]:
#converting excel data into json data
df.to_json("test.json")

In [52]:
pwd

'C:\\Users\\Md Sirajul Islam\\Full Stack DataScience Paid Ineuron\\Module 1 python\\Pandas'

In [55]:
df=pd.read_excel(r"Attribute DataSet.xlsx")

In [59]:
df.to_csv("E://Files")

PermissionError: [Errno 13] Permission denied: 'E:/Files'

In [60]:
df.to_CSV("E://test123.csv", sep= "#")

AttributeError: 'DataFrame' object has no attribute 'to_CSV'